### PR TITLE
add ralph.txt

### PR DESCRIPTION
**Pull request by skaramooch**
uwuwuwu pulling 4 yelan

### CODE REVIEW

**Review by earairl — COMMENTED** [review]
congrts

**Review by NaHyung2ya — COMMENTED** [review]
YEEYYY

**Review by FranchescaMei — APPROVED** [review]
wew congratz

**Review by earairl — APPROVED** [review]
wowwww

**Review by NaHyung2ya — APPROVED** [review]
YEEY

**Review by skaramooch — COMMENTED** [review]
wao

**Pull request merged**
